config/routes.rb
Rails.application.routes.draw do

  devise_for :clients, path: 'clients', controllers: { registrations: "clients/registrations" }
  resources :clients, only: [:edit, :update]

  devise_for :mourners, path: 'mourners', controllers: { registrations: "mourners/registrations" }
  resources :mourners, only: [:index, :show, :edit, :update] do
    resources :prestations, only: [:create, :destroy, :update]
  end
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :prestations
  has_many :mourners, through: :prestations
end

app/controllers/clients/confirmations_controller.rb
# frozen_string_literal: true

class Clients::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/clients/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Clients::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/clients/passwords_controller.rb
# frozen_string_literal: true

class Clients::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/clients/registrations_controller.rb
# frozen_string_literal: true

class Clients::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :location, :profile_picture, :account_number])
  end
end

app/controllers/clients/sessions_controller.rb
# frozen_string_literal: true

class Clients::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/clients/unlocks_controller.rb
# frozen_string_literal: true

class Clients::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_client!
  skip_before_action :authenticate_client!, only: [:edit, :update]

  def edit
    @client = Client.find(params[:id])
    authorize @client
    @prestations = @client.prestations
  end

  def update
    @client = Client.find(params[:id])
    authorize @client if pundit_user == @client
    @client.update(client_params)
    redirect_to edit_client_path(@client)
  end

  private

  def client_params
    params.require(:client).permit(:first_name, :last_name, :account_number, :location, :profile_picture)
  end

  def pundit_user
    current_client || current_mourner
  end
end

app/views/clients/create.html.erb
<h1>Clients#create</h1>
<p>Find me in app/views/clients/create.html.erb</p>

<p>just a test</p>

app/views/clients/destroy.html.erb
<h1>Clients#destroy</h1>
<p>Find me in app/views/clients/destroy.html.erb</p>

app/views/clients/edit.html.erb
<div class="container">
  <h1 class="mt-3 ml-3" id="h2-banner">Your Client Dashboard</h1>
  <div class="row">
    <div class="col-3 mt-3 card">
      <div class="text-center">
        <h2>Your profile</h2>
        <p>Update your data if needed</p>
      </div>
    <%= simple_form_for @client do |f| %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :account_number %>
      <div class="text-center">
        <%= f.button :submit, "Update profile", class: "btn btn-secondary btn-lg", id: "client-btn" %>
      </div>
    <% end %>
    </div>
    <div class="col-9 mt-3">
      <div class="card-category">
        <div class="d-flex align-items-end">
          <%= link_to mourners_path, style: "margin-bottom: 10px;", id: "client-link" do %>
            <i class="fas fa-angle-right"></i> See all mourners available
          <% end %>
        </div>
        <div class="card-background" style="background-image: url('<%= image_path("mourning_ladies.svg") %>')" ></div>
      </div>
      <h1 class="mt-4" id="h2-banner" style="font-size: 35px">Reservation History</h1>
      <div class="card">
​        <% if current_client.prestations.empty? %>

          <div style="text-align: center">
            <img src="https://media.giphy.com/media/3o7buagJzUFQWpb2PC/giphy.gif" style="width: 30%">
            <p>No reservation done yet...</p>
            <%= link_to 'Hire a professional mourner !', mourners_path, class: "btn btn-secondary btn-lg", id: "client-btn" %>
          </div>

​        <% else %>

          <div class="prestations">
            <p class="text-center">
              Keep an eye below on the different requests for services made to our mourners...
            </p>

            <% @prestations.each do |prestation| %>
              <div data-prestation-id="<%= prestation.id %>">
                <div class="notification mt-3">
                  <%= cl_image_tag prestation.mourner.photo, class: "avatar-large" %>
                  <div class="notification-content">
                    <p>
                      <small><%= prestation.date %></small>
                    </p>

                    <p>
                      <strong><%= prestation.mourner.first_name %> <%= prestation.mourner.last_name %></strong>
                    </p>

                    <p>
                      <small>
                        <i class="fas fa-map-marker-alt"></i>
                        <%= prestation.location %> |
                        <i class="far fa-envelope"></i>
                        <%= prestation.mourner.email %> |
                        <i class="fas fa-coins"></i>
                        <%= prestation.price %> € |
                        <%= link_to mourner_path(prestation.mourner) do %>
                        <i class="fas fa-address-card"></i>
                          See profile
                      <% end %>
                      </small>
                    </p>

                    <p>
                      <%= prestation.mourner.first_name %>
                       looks forward to meeting you in
                       <%= prestation.location %> !
                    </p>

                    <% case prestation.status %>
                    <% when 0 %>
                      <span class="badge badge-success badge-pending">Pending</span>
                    <% when 1 %>
                      <span class="badge badge-success badge-accepted">Accepted</span>
                    <% end %>
                  </div>

                  <% if prestation.status == 0 %>
                    <div class="notification-actions">
                      <%= link_to mourner_prestation_path(prestation.mourner, prestation), method: :delete, :data => {:confirm => "Do you really want to cancel it?"}, remote: :true do %>
                        <i class="fas fa-trash"></i>
                         Cancel
                      <% end %>
                    </div>
                  <% end %>
                </div>
            <% end %>
                <div style="text-align: center">
                  <%= link_to "Another funeral coming?", mourners_path, class: "btn btn-secondary btn-lg mt-3", id: "client-btn" %>
                </div>
              </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/clients/index.html.erb
<h1>Clients#index</h1>
<p>Find me in app/views/clients/index.html.erb</p>
<%= link_to "Sign-out", destroy_client_session_path, method: :delete %>

app/views/clients/new.html.erb
<h1>Clients#new</h1>
<p>Find me in app/views/clients/new.html.erb</p>

app/views/clients/show.html.erb
<h1>Clients#show</h1>
<p>Find me in app/views/clients/show.html.erb</p>

app/views/clients/update.html.erb
<h1>Clients#update</h1>
<p>Find me in app/views/clients/update.html.erb</p>