config/routes.rb
Rails.application.routes.draw do

  devise_for :clients, path: 'clients', controllers: { registrations: "clients/registrations" }
  resources :clients, only: [:edit, :update]

  devise_for :mourners, path: 'mourners', controllers: { registrations: "mourners/registrations" }
  resources :mourners, only: [:index, :show, :edit, :update] do
    resources :prestations, only: [:create, :destroy, :update]
  end
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/home.html.erb
<div class="banner">
    <div class="container">
      <h1 id="h1-banner" style="text-align: center">Stop crying alone at funerals</h1>
      <div class ="card-row-home">
        <div class="col-6 text-center mt-5">
          <div class="card" id="client-card" data-aos="fade-up-right" data-aos-duration="4000">
            <%= image_tag "client.svg", class: "card-images" %>
            <p>Need someone's presence for a funeral ceremony ?</p>
            <%= link_to 'Hire a professional mourner !', new_client_registration_path, class: "btn btn-secondary btn-lg", id: "client-btn", style: "font-size: 20px; padding: 8px 16px" %>
          </div>
        </div>
        <div class="col-6 text-center mt-5">
          <div class="card" id="mourner-card" data-aos="fade-up-left" data-aos-duration="4000">
            <%= image_tag "mourner.svg", class: "card-images" %>
            <p>Need to earn some money ?</p>
            <%= link_to 'Become a professional mourner !', new_mourner_registration_path, class: "btn btn-secondary btn lg", id: "mourner-btn", style: "font-size: 20px; padding: 8px 16px" %>
          </div>
        </div>
      </div>
    </div>
</div>