config/routes.rb
Rails.application.routes.draw do

  devise_for :clients, path: 'clients', controllers: { registrations: "clients/registrations" }
  resources :clients, only: [:edit, :update]

  devise_for :mourners, path: 'mourners', controllers: { registrations: "mourners/registrations" }
  resources :mourners, only: [:index, :show, :edit, :update] do
    resources :prestations, only: [:create, :destroy, :update]
  end
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Easy Coffin : death has never been so easy</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag  %>

    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <!-- Add the slick-theme.css if you want default styling -->
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/gh/kenwheeler/slick@1.8.1/slick/slick.css"/>
    <!-- Add the slick-theme.css if you want default styling -->
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/gh/kenwheeler/slick@1.8.1/slick/slick-theme.css"/>
  </head>
  <body>
  <nav class="navbar d-flex justify-content-between">
    <a class="navbar-brand" href="/">
      <%= image_tag 'EASYCOFFIN_logo1.png' %>
    </a>
    <div class="row">
    <% if !user_signed_in? %>
      <div class="dropdown show">
        <a class="btn btn-secondary dropdown-toggle mr-2" style="background-color: black" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Log In
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
          <a class="dropdown-item" href="/clients/sign_in">As a client</a>
          <a class="dropdown-item" href="/mourners/sign_in">As a mourner</a>
        </div>
      </div>

    <% else %>

        <% if mourner_signed_in?  %>
          <%= link_to "My Mourner Dashboard", edit_mourner_path(current_mourner), class: "btn btn-secondary mr-2", id:"mourner-btn" %>
          <%= link_to "Log out", destroy_mourner_session_path, method: :delete, class: "btn btn-secondary mr-2", style: "background-color: black" %>
        <% elsif client_signed_in? %>
          <%= link_to "My Client Dashboard", edit_client_path(current_client), class: "btn btn-secondary mr-2", id:"client-btn" %>
          <%= link_to "Log out", destroy_client_session_path, method: :delete, class: "btn btn-secondary mr-2", style: "background-color: black" %>
        <% end %>
    <% end %>
  </div>
  </nav>
    <%= yield %>
    <p class="notice"></p>
    <p class="alert"><%= alert %></p>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
      AOS.init();
    </script>
    <%= render 'shared/flashes' %>
  </body>
</html>